import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { Providers } from "@/components/providers";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const founders_grotesk = localFont({
  variable: "--font-fg",
  src: [
    {
      path: "../../public/fonts/FoundersGrotesk-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/FoundersGrotesk-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/FoundersGrotesk-Semibold.otf",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${founders_grotesk.variable}`}>
        <Providers>
          <Header />
          <div className="h-screen flex flex-col">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
